/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../Components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/DropDownMenu`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/PlayerProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/speech` | `/speech`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../Components/CustomButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../Components/DropDownMenu`; params?: Router.UnknownOutputParams; } | { pathname: `/../Components/PlayerProgressBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../Components/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/speech` | `/speech`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../Components/CustomButton${`?${string}` | `#${string}` | ''}` | `/../Components/DropDownMenu${`?${string}` | `#${string}` | ''}` | `/../Components/PlayerProgressBar${`?${string}` | `#${string}` | ''}` | `/../Components/index${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/speech${`?${string}` | `#${string}` | ''}` | `/speech${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../constants/data${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../Components/CustomButton`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/DropDownMenu`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/PlayerProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/../Components/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/speech` | `/speech`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; };
    }
  }
}
